DIALOGFLOW_PROJECT_ID = 'sinuous-axiom-257104'
DIALOGFLOW_LANGUAGE_CODE = 'en-US'
GOOGLE_APPLICATION_CREDENTIALS = 'service-acc-creds.json'

PROTECTED_INTENTS = set([
    "account.create.q2",
    "get-stock-info"
])

FB_ACCESS_TOKEN = "EAAkZBBLkY9IUBAIOkNBDvhTpB39SYCHackNVgVfFjrQrfrfWduBWMZAnHtlmGA5ouTr33nqJZCx4ucueMLTZAldMBksjUalZAR2ZA1nQyE7PxAz63UXaEhT23k1WPDWbQQj0ZB9VElJU4OQ5QHhl6hucES4mFCsLAScdJ546IHoPYdli162Kvq1"
FB_VERIFY_TOKEN = "test"